### ISSUE TITLE
fedora URL has changed

### ISSUE THREAD

**Issue by bigHosting** [lwindolf/lpvs#3]
I wanted to give it a try today but it seems the url to pull security advisories has changed as the page redirects to something else ?

Thanks

**Comment by lwindolf** [comment]
I fixed the Fedora URI in 41e960b

**Comment by lwindolf** [comment]
Thanks for reporting this. Please note that I gave up on this tool in favour of (https://github.com/lwindolf/polscan) which at the moment is Debian only, but could be easily extended to analyze Fedora CVEs too.
